(()=>{
const D=window.KAZAN,$=id=>document.getElementById(id),status=$('status');
if(!D||!window.L){status.textContent='Не удалось загрузить карту';return}
const tabs=$('tabs'),sheet=$('sheet'),list=$('list'),title=$('title'),subtitle=$('subtitle'),locateBtn=$('locateBtn'),followBtn=$('followBtn'),routeCard=$('routeCard'),routeTitle=$('routeTitle'),routeMeta=$('routeMeta'),routeBtn=$('routeBtn'),clearRouteBtn=$('clearRouteBtn'),toggle=$('toggle');
const labels={all:['Все','Все точки и варианты'],d27:['27 июля','Баумана и развлечения'],d28:['28 июля','Кабан и Старо-Татарская слобода'],d29:['29 июля','Голубые озёра и Казанка'],d30:['30 июля','Кремль и набережная'],d31:['31 июля','Парки и арт-пространства'],backup:['Дождь','Океанариум'],yosh:['Йошкар-Ола','Отдельный день']},order=['all','d27','d28','d29','d30','d31','backup','yosh'];
let active='d27',selectedItem=null,selectedMarker=null,userLatLng=null,userMarker=null,accuracyCircle=null,watchId=null,followLocation=true,routeLine=null,routeFallbackLine=null,routeRequestId=0,lastRouteOrigin=null,lastRouteAt=0,pendingRouteItem=null,statusTimer=null;
function say(text,sticky=false){status.textContent=text;status.classList.add('visible');clearTimeout(statusTimer);if(!sticky)statusTimer=setTimeout(()=>status.classList.remove('visible'),2400)}
const map=L.map('map',{zoomControl:true,preferCanvas:true,zoomAnimation:true}).setView([55.797,49.122],12);
let tileErrors=0,baseLayer=L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{subdomains:'abcd',maxZoom:20,detectRetina:true,updateWhenIdle:true,keepBuffer:2,attribution:'© OpenStreetMap © CARTO'}).addTo(map);
baseLayer.on('load',()=>say('Карта готова'));
baseLayer.on('tileerror',()=>{tileErrors++;if(tileErrors===6){map.removeLayer(baseLayer);baseLayer=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,updateWhenIdle:true,keepBuffer:2,attribution:'© OpenStreetMap'}).addTo(map);say('Переключаю подложку…')}});
const layers={},markers=[];order.slice(1).concat('stay').forEach(d=>layers[d]=L.layerGroup());const color=d=>D.days[d]?.[2]||'#111827';
function icon(x,selected=false){const fill=selected?'#EF4444':color(x[1]),label=x[1]==='stay'?'♥':x[2];return L.divIcon({className:'marker',html:`<i class="${selected?'selected':''}" style="background:${fill}">${label}</i>`,iconSize:selected?[40,40]:[32,32],iconAnchor:selected?[20,20]:[16,16],popupAnchor:[0,selected?-18:-13]})}
function externalNav(x){const y=`https://yandex.ru/maps/?rtext=${userLatLng?`${userLatLng.lat},${userLatLng.lng}`:''}~${x[6]},${x[7]}&rtt=auto`,g=`https://www.google.com/maps/dir/?api=1&destination=${x[6]},${x[7]}${userLatLng?`&origin=${userLatLng.lat},${userLatLng.lng}`:''}`,d=`https://2gis.ru/kazan/routeSearch/rsType/car/to/${x[7]},${x[6]}`;return `<div class="links"><a target="_blank" rel="noopener" href="${y}">Яндекс</a><a target="_blank" rel="noopener" href="${g}">Google</a><a target="_blank" rel="noopener" href="${d}">2ГИС</a></div>`}
function popupHtml(x){return `<b>${x[2]}. ${x[4]}</b><br><small>${x[3]} · ${x[5]||''}</small>${x[8]?`<div class="warn">${x[8]}</div>`:''}<button class="popup-route">Маршрут сюда</button>${externalNav(x)}`}
D.items.forEach(x=>{const m=L.marker([x[6],x[7]],{icon:icon(x),riseOnHover:true}).bindPopup(popupHtml(x)).bindTooltip(`${x[2]}. ${x[4]}`,{direction:'top',offset:[0,-17],className:'lab'});m.on('click',()=>selectPin(x,m));m.on('popupopen',e=>{const b=e.popup.getElement()?.querySelector('.popup-route');if(b)b.onclick=()=>buildRouteTo(x)});m.addTo(layers[x[1]]);markers.push([x,m])});
const byKey=Object.fromEntries(D.items.map(x=>[x[0],x]));Object.entries(D.routes).forEach(([d,keys])=>L.polyline(keys.map(k=>[byKey[k][6],byKey[k][7]]),{color:color(d),weight:4,opacity:.48,dashArray:'7 9'}).addTo(layers[d]));D.areas.forEach(a=>L.circle(a.center,{radius:a.radius,color:color(a.day),weight:2,fillColor:color(a.day),fillOpacity:.055,opacity:.32,interactive:false}).addTo(layers[a.day]));
const currentItems=()=>D.items.filter(x=>active==='all'?x[1]!=='yosh':x[1]===active);
function renderTabs(){tabs.innerHTML='';order.forEach(d=>{const b=document.createElement('button');b.textContent=labels[d][0];b.className=d===active?'on':'';b.onclick=()=>selectDay(d);tabs.appendChild(b)})}
function renderList(){list.innerHTML='';currentItems().forEach(x=>{const el=document.createElement('div'),sel=selectedItem===x;el.className=`stop${sel?' selected-stop':''}`;el.innerHTML=`<div class="n" style="background:${sel?'#EF4444':color(x[1])}">${x[2]}</div><div><b>${x[4]}</b><span>${x[3]} · ${x[5]||'Открытая территория'}</span><div class="row-actions"><button class="mini-route">Маршрут</button>${externalNav(x)}</div></div>`;el.onclick=e=>{if(e.target.tagName==='A')return;if(e.target.classList.contains('mini-route')){selectPin(x,markers.find(z=>z[0]===x)?.[1]);buildRouteTo(x);return}const p=markers.find(z=>z[0]===x)?.[1];selectPin(x,p);map.setView([x[6],x[7]],16);p?.openPopup();setSheetOpen(false)};list.appendChild(el)})}
function updateLayers(){Object.entries(layers).forEach(([d,l])=>{const on=d==='stay'||(active==='all'?d!=='yosh':d===active);if(on&&!map.hasLayer(l))l.addTo(map);if(!on&&map.hasLayer(l))map.removeLayer(l)});updateLabels()}
function updateLabels(){const show=map.getZoom()>=15;markers.forEach(([x,m])=>{if((show&&map.hasLayer(m))||m===selectedMarker)m.openTooltip();else m.closeTooltip()})}
function fitDay(){const a=currentItems().concat(D.items.filter(x=>x[1]==='stay'));if(!a.length)return;map.fitBounds(L.latLngBounds(a.map(x=>[x[6],x[7]])).pad(.12),{maxZoom:active==='all'?11:14,paddingTopLeft:[18,82],paddingBottomRight:[18,128]})}
function selectDay(d){active=d;title.textContent=labels[d][0];subtitle.textContent=labels[d][1];renderTabs();renderList();updateLayers();setTimeout(fitDay,50)}
function setSheetOpen(open){sheet.classList.toggle('open',open);document.body.classList.toggle('sheet-open',open);toggle.textContent=open?'Скрыть':'План';setTimeout(()=>map.invalidateSize(),230)}
function selectPin(x,m){if(selectedMarker&&selectedItem)selectedMarker.setIcon(icon(selectedItem));selectedItem=x;selectedMarker=m||markers.find(z=>z[0]===x)?.[1]||null;if(selectedMarker)selectedMarker.setIcon(icon(x,true));routeTitle.textContent=x[4];routeMeta.textContent=userLatLng?'Точка выбрана. Можно построить маршрут.':'Точка выбрана. Включите GPS для маршрута.';routeCard.classList.add('show');renderList();updateLabels()}
function createUserMarker(latlng,accuracy){const userIcon=L.divIcon({className:'user-location',html:'<span><i></i></span>',iconSize:[28,28],iconAnchor:[14,14]});if(!userMarker){userMarker=L.marker(latlng,{icon:userIcon,zIndexOffset:2000}).addTo(map).bindPopup('Вы находитесь здесь');accuracyCircle=L.circle(latlng,{radius:accuracy||0,color:'#2563EB',weight:1,fillColor:'#3B82F6',fillOpacity:.1,opacity:.32,interactive:false}).addTo(map)}else{userMarker.setLatLng(latlng);accuracyCircle.setLatLng(latlng).setRadius(accuracy||0)}}
function startLocation(){if(!navigator.geolocation){say('GPS недоступен',true);return}if(watchId!==null){followLocation=true;followBtn.classList.add('on');if(userLatLng)map.setView(userLatLng,16);return}say('Запрашиваю доступ к GPS…',true);locateBtn.classList.add('loading');watchId=navigator.geolocation.watchPosition(pos=>{const next=L.latLng(pos.coords.latitude,pos.coords.longitude);userLatLng=next;createUserMarker(next,pos.coords.accuracy);locateBtn.classList.remove('loading');locateBtn.classList.add('active');say(`GPS: точность ±${Math.round(pos.coords.accuracy)} м`,true);if(followLocation)map.setView(next,Math.max(map.getZoom(),16));if(pendingRouteItem){const p=pendingRouteItem;pendingRouteItem=null;buildRouteTo(p)}else if(selectedItem&&shouldRefreshRoute(next))buildRouteTo(selectedItem,true);else if(selectedItem&&!routeLine&&!routeFallbackLine)routeMeta.textContent='GPS включён. Нажмите «Маршрут».'},err=>{locateBtn.classList.remove('loading');watchId=null;say(({1:'Доступ к геолокации запрещён',2:'Не удалось определить местоположение',3:'GPS отвечает слишком долго'})[err.code]||'Ошибка GPS',true)},{enableHighAccuracy:true,maximumAge:5000,timeout:15000})}
function shouldRefreshRoute(next){return lastRouteOrigin&&next.distanceTo(lastRouteOrigin)>100&&Date.now()-lastRouteAt>15000}
function clearRoute(){routeRequestId++;if(routeLine){map.removeLayer(routeLine);routeLine=null}if(routeFallbackLine){map.removeLayer(routeFallbackLine);routeFallbackLine=null}lastRouteOrigin=null;lastRouteAt=0;routeMeta.textContent=selectedItem?(userLatLng?'Маршрут очищен.':'Включите GPS для маршрута.'):'Выберите точку.'}
const fmtDist=m=>m<1000?`${Math.round(m)} м`:`${(m/1000).toFixed(m<10000?1:0)} км`,fmtTime=s=>{const min=Math.max(1,Math.round(s/60));return min<60?`${min} мин`:`${Math.floor(min/60)} ч${min%60?` ${min%60} мин`:''}`};
async function buildRouteTo(x,silent=false){selectPin(x,markers.find(z=>z[0]===x)?.[1]);if(!userLatLng){pendingRouteItem=x;startLocation();routeMeta.textContent='Разрешите GPS — маршрут построится автоматически.';return}const id=++routeRequestId;routeBtn.disabled=true;routeBtn.textContent='Строю…';if(!silent)say('Строю маршрут…',true);const dest=L.latLng(x[6],x[7]),url=`https://router.project-osrm.org/route/v1/driving/${userLatLng.lng},${userLatLng.lat};${dest.lng},${dest.lat}?overview=full&geometries=geojson&steps=false`;try{const res=await fetch(url);if(!res.ok)throw Error();const json=await res.json();if(id!==routeRequestId)return;const route=json.routes?.[0];if(!route)throw Error();if(routeLine)map.removeLayer(routeLine);if(routeFallbackLine){map.removeLayer(routeFallbackLine);routeFallbackLine=null}routeLine=L.geoJSON(route.geometry,{style:{color:'#2563EB',weight:7,opacity:.92,lineCap:'round',lineJoin:'round'}}).addTo(map);routeMeta.textContent=`На машине: ${fmtDist(route.distance)} · ${fmtTime(route.duration)}`;map.fitBounds(routeLine.getBounds().pad(.12),{paddingTopLeft:[18,86],paddingBottomRight:[18,150],maxZoom:16});lastRouteOrigin=L.latLng(userLatLng.lat,userLatLng.lng);lastRouteAt=Date.now();say('Маршрут построен')}catch(e){if(id!==routeRequestId)return;if(routeLine){map.removeLayer(routeLine);routeLine=null}if(routeFallbackLine)map.removeLayer(routeFallbackLine);routeFallbackLine=L.polyline([userLatLng,dest],{color:'#2563EB',weight:5,opacity:.8,dashArray:'8 8'}).addTo(map);routeMeta.textContent=`Показано направление: ${fmtDist(userLatLng.distanceTo(dest))}`;map.fitBounds(routeFallbackLine.getBounds().pad(.2),{paddingTopLeft:[18,86],paddingBottomRight:[18,150],maxZoom:16});say('Маршрутизатор недоступен — показано направление')}finally{if(id===routeRequestId){routeBtn.disabled=false;routeBtn.textContent='Маршрут'}}}
locateBtn.onclick=startLocation;followBtn.onclick=()=>{followLocation=!followLocation;followBtn.classList.toggle('on',followLocation);if(followLocation&&userLatLng)map.setView(userLatLng,16)};routeBtn.onclick=()=>selectedItem&&buildRouteTo(selectedItem);clearRouteBtn.onclick=clearRoute;map.on('dragstart',()=>{followLocation=false;followBtn.classList.remove('on')});map.on('zoomend',updateLabels);$('handle').onclick=()=>setSheetOpen(!sheet.classList.contains('open'));toggle.onclick=()=>setSheetOpen(!sheet.classList.contains('open'));
selectDay('d27');setSheetOpen(false);setTimeout(()=>map.invalidateSize(),150);
})();