(()=>{
  const D=window.KAZAN,Q=id=>document.getElementById(id),status=Q('status');
  if(!D||!window.L){status.textContent='Не удалось загрузить карту. Обновите страницу.';return}

  const tabs=Q('tabs'),sheet=Q('sheet'),list=Q('list'),title=Q('title'),subtitle=Q('subtitle'),locateBtn=Q('locateBtn'),followBtn=Q('followBtn'),toggleBtn=Q('toggle');
  const labels={all:['Все','Все точки и варианты'],d27:['27 июля','Баумана и развлечения'],d28:['28 июля','Кабан и Старо-Татарская слобода'],d29:['29 июля','Голубые озёра и Казанка'],d30:['30 июля','Кремль и набережная'],d31:['31 июля','Парки и арт-пространства'],backup:['Дождь','Океанариум'],yosh:['Йошкар-Ола','Отдельный день']},order=['all','d27','d28','d29','d30','d31','backup','yosh'];
  const mobile=matchMedia('(max-width:799px)').matches;

  const uiStyle=document.createElement('style');
  uiStyle.textContent='.route-card{display:none!important}.sheet.has-selection{--peek:126px!important}.inline-route-info{margin-top:8px;padding:8px 10px;border-radius:10px;background:#eff6ff;color:#1d4ed8;font-size:12px;font-weight:700;line-height:1.3}.active-route-stop{box-shadow:inset 0 0 0 1px #bfdbfe}.mini-clear{border:0;border-radius:8px;background:#e8edf3;color:#111827;padding:7px 10px;font-size:11px;font-weight:800}.mini-route:disabled{opacity:.55}';
  document.head.appendChild(uiStyle);

  let active='d27',selectedItem=null,selectedMarker=null,userLatLng=null,userMarker=null,accuracyCircle=null,watchId=null,followLocation=true,routeLine=null,routeFallbackLine=null,routeRequestId=0,lastRouteOrigin=null,lastRouteAt=0,pendingRouteItem=null,statusTimer=null,activeRouteItem=null,routeSummary='',routeBusy=false;

  function setStatus(text,sticky=false){status.textContent=text;status.classList.remove('hide');clearTimeout(statusTimer);if(!sticky)statusTimer=setTimeout(()=>status.classList.add('hide'),2600)}
  function setSheetOpen(open){sheet.classList.toggle('open',open);toggleBtn.textContent=open?'Свернуть':'Открыть';toggleBtn.setAttribute('aria-expanded',String(open));if(open)setTimeout(()=>map.invalidateSize(),80)}

  const map=L.map('map',{zoomControl:true,preferCanvas:true,fadeAnimation:false,markerZoomAnimation:false,zoomAnimation:!mobile}).setView([55.797,49.122],12);
  const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap',updateWhenIdle:mobile,keepBuffer:1}).addTo(map);
  tiles.once('load',()=>setStatus('Карта готова'));
  tiles.on('tileerror',()=>setStatus('Часть карты не загрузилась. Проверьте интернет.',true));

  const layers={},markers=[];order.slice(1).concat('stay').forEach(day=>layers[day]=L.layerGroup());
  const color=day=>D.days[day]?.[2]||'#111827';
  function icon(item,selected=false){const fill=selected?'#ef4444':color(item[1]),label=item[1]==='stay'?'♥':item[2];return L.divIcon({className:'marker',html:`<i class="${selected?'selected':''}" style="background:${fill}">${label}</i>`,iconSize:selected?[40,40]:[32,32],iconAnchor:selected?[20,20]:[16,16],popupAnchor:[0,selected?-18:-13]})}
  function externalNav(item){const yandex=`https://yandex.ru/maps/?rtext=${userLatLng?`${userLatLng.lat},${userLatLng.lng}`:''}~${item[6]},${item[7]}&rtt=auto`,google=`https://www.google.com/maps/dir/?api=1&destination=${item[6]},${item[7]}${userLatLng?`&origin=${userLatLng.lat},${userLatLng.lng}`:''}`,gis=`https://2gis.ru/kazan/routeSearch/rsType/car/to/${item[7]},${item[6]}`;return `<div class="links"><a target="_blank" rel="noopener" href="${yandex}">Яндекс</a><a target="_blank" rel="noopener" href="${google}">Google</a><a target="_blank" rel="noopener" href="${gis}">2ГИС</a></div>`}
  function popupHtml(item){return `<b>${item[2]}. ${item[4]}</b><br><small>${item[3]} · ${item[5]||''}</small>${item[8]?`<div class="warn">${item[8]}</div>`:''}<button class="popup-route">Маршрут сюда</button>${externalNav(item)}`}

  D.items.forEach(item=>{const marker=L.marker([item[6],item[7]],{icon:icon(item),riseOnHover:true}).bindPopup(popupHtml(item));if(!mobile)marker.bindTooltip(`${item[2]}. ${item[4]}`,{permanent:true,direction:'top',offset:[0,-17],className:'lab'});marker.on('click',()=>selectPin(item,marker));marker.on('popupopen',event=>{const button=event.popup.getElement()?.querySelector('.popup-route');if(button)button.onclick=()=>buildRouteTo(item)});marker.addTo(layers[item[1]]);markers.push([item,marker])});

  const byKey=Object.fromEntries(D.items.map(item=>[item[0],item]));
  Object.entries(D.routes).forEach(([day,keys])=>L.polyline(keys.map(key=>[byKey[key][6],byKey[key][7]]),{color:color(day),weight:4,opacity:.5,dashArray:'7 8',interactive:false}).addTo(layers[day]));
  D.areas.forEach(area=>L.circle(area.center,{radius:area.radius,color:color(area.day),weight:2,fillColor:color(area.day),fillOpacity:.06,opacity:.32,interactive:false}).addTo(layers[area.day]));

  const visibleItems=()=>D.items.filter(item=>active==='all'?item[1]!=='yosh':item[1]===active);
  function renderTabs(){tabs.innerHTML='';order.forEach(day=>{const button=document.createElement('button');button.textContent=labels[day][0];button.className=day===active?'on':'';button.onclick=()=>selectDay(day);tabs.appendChild(button)})}
  function renderList(){const fragment=document.createDocumentFragment();list.innerHTML='';visibleItems().forEach(item=>{const element=document.createElement('div'),chosen=selectedItem===item,isRoute=activeRouteItem===item,hasBuiltRoute=isRoute&&Boolean(routeLine||routeFallbackLine);element.className=`stop${chosen?' selected-stop':''}${isRoute?' active-route-stop':''}`;const routeInfo=isRoute&&routeSummary?`<div class="inline-route-info">${routeSummary}</div>`:'',clearButton=hasBuiltRoute?'<button class="mini-clear" type="button">Сбросить</button>':'';element.innerHTML=`<div class="n" style="background:${chosen?'#ef4444':color(item[1])}">${item[2]}</div><div><b>${item[4]}</b><span>${item[3]} · ${item[5]||'Открытая территория'}</span>${routeInfo}<div class="row-actions"><button class="mini-route" type="button" ${routeBusy&&isRoute?'disabled':''}>${routeBusy&&isRoute?'Строю…':hasBuiltRoute?'Перестроить':'Маршрут'}</button>${clearButton}</div></div>`;element.onclick=event=>{if(event.target.closest('a'))return;if(event.target.classList.contains('mini-clear')){event.stopPropagation();clearRoute();return}const marker=markers.find(pair=>pair[0]===item)?.[1];selectPin(item,marker);if(event.target.classList.contains('mini-route')){event.stopPropagation();buildRouteTo(item);return}map.setView([item[6],item[7]],16);marker?.openPopup();setSheetOpen(false)};fragment.appendChild(element)});list.appendChild(fragment)}
  function updateLayers(){Object.entries(layers).forEach(([day,layer])=>{const show=day==='stay'||(active==='all'?day!=='yosh':day===active);if(show&&!map.hasLayer(layer))layer.addTo(map);if(!show&&map.hasLayer(layer))map.removeLayer(layer)})}
  function fit(){const items=visibleItems().concat(D.items.filter(item=>item[1]==='stay'));if(!items.length)return;map.fitBounds(L.latLngBounds(items.map(item=>[item[6],item[7]])).pad(.12),{maxZoom:active==='all'?11:14,paddingTopLeft:[20,80],paddingBottomRight:[20,145]})}
  function selectDay(day){active=day;title.textContent=labels[day][0];subtitle.textContent=labels[day][1];renderTabs();renderList();updateLayers();requestAnimationFrame(()=>setTimeout(fit,30))}
  function selectPin(item,marker){if(selectedMarker&&selectedItem){selectedMarker.setIcon(icon(selectedItem,false));if(mobile)selectedMarker.closeTooltip()}selectedItem=item;selectedMarker=marker||markers.find(pair=>pair[0]===item)?.[1]||null;if(selectedMarker){selectedMarker.setIcon(icon(item,true));if(mobile)selectedMarker.unbindTooltip().bindTooltip(item[4],{permanent:true,direction:'top',offset:[0,-21],className:'lab'}).openTooltip()}renderList()}

  function createUserMarker(latlng,accuracy){const userIcon=L.divIcon({className:'user-location',html:'<span><i></i></span>',iconSize:[28,28],iconAnchor:[14,14]});if(!userMarker){userMarker=L.marker(latlng,{icon:userIcon,zIndexOffset:2000}).addTo(map).bindPopup('Вы находитесь здесь');accuracyCircle=L.circle(latlng,{radius:accuracy||0,color:'#2563eb',weight:1,fillColor:'#3b82f6',fillOpacity:.1,opacity:.35,interactive:false}).addTo(map)}else{userMarker.setLatLng(latlng);accuracyCircle.setLatLng(latlng).setRadius(accuracy||0)}}
  function startLocation(){if(!navigator.geolocation){setStatus('GPS недоступен в этом браузере',true);return}if(watchId!==null){followLocation=true;followBtn.classList.add('on');if(userLatLng)map.setView(userLatLng,16);return}setStatus('Запрашиваю доступ к GPS…',true);locateBtn.classList.add('loading');watchId=navigator.geolocation.watchPosition(position=>{const next=L.latLng(position.coords.latitude,position.coords.longitude);userLatLng=next;createUserMarker(next,position.coords.accuracy);locateBtn.classList.remove('loading');locateBtn.classList.add('active');setStatus(`GPS: точность ±${Math.round(position.coords.accuracy)} м`);if(followLocation)map.setView(next,Math.max(map.getZoom(),16));if(pendingRouteItem){const pending=pendingRouteItem;pendingRouteItem=null;buildRouteTo(pending)}else if(activeRouteItem&&shouldRefreshRoute(next))buildRouteTo(activeRouteItem,true)},error=>{locateBtn.classList.remove('loading');watchId=null;setStatus(({1:'Доступ к геолокации запрещён',2:'Не удалось определить местоположение',3:'GPS отвечает слишком долго'})[error.code]||'Ошибка GPS',true)},{enableHighAccuracy:true,maximumAge:5000,timeout:15000})}
  function shouldRefreshRoute(next){return lastRouteOrigin&&next.distanceTo(lastRouteOrigin)>100&&Date.now()-lastRouteAt>15000}
  function clearRoute(){routeRequestId++;if(routeLine){map.removeLayer(routeLine);routeLine=null}if(routeFallbackLine){map.removeLayer(routeFallbackLine);routeFallbackLine=null}lastRouteOrigin=null;lastRouteAt=0;pendingRouteItem=null;activeRouteItem=null;routeSummary='';routeBusy=false;renderList();setStatus('Маршрут сброшен')}
  const formatDistance=meters=>meters<1000?`${Math.round(meters)} м`:`${(meters/1000).toFixed(meters<10000?1:0)} км`;
  function formatDuration(seconds){const minutes=Math.max(1,Math.round(seconds/60));return minutes<60?`${minutes} мин`:`${Math.floor(minutes/60)} ч${minutes%60?` ${minutes%60} мин`:''}`}

  async function buildRouteTo(item,silent=false){selectPin(item,markers.find(pair=>pair[0]===item)?.[1]);activeRouteItem=item;routeBusy=true;routeSummary='Подготовка маршрута…';renderList();if(!userLatLng){pendingRouteItem=item;startLocation();routeSummary='Разрешите доступ к GPS — маршрут построится автоматически';routeBusy=false;renderList();return}const requestId=++routeRequestId,destination=L.latLng(item[6],item[7]);routeSummary='Строю маршрут…';renderList();if(!silent)setStatus('Строю маршрут…',true);try{const url=`https://router.project-osrm.org/route/v1/driving/${userLatLng.lng},${userLatLng.lat};${destination.lng},${destination.lat}?overview=full&geometries=geojson&steps=false`,response=await fetch(url,{mode:'cors'});if(!response.ok)throw new Error();const json=await response.json();if(requestId!==routeRequestId)return;const route=json.routes?.[0];if(!route)throw new Error();if(routeLine)map.removeLayer(routeLine);if(routeFallbackLine){map.removeLayer(routeFallbackLine);routeFallbackLine=null}routeLine=L.geoJSON(route.geometry,{style:{color:'#2563eb',weight:7,opacity:.9,lineCap:'round',lineJoin:'round'}}).addTo(map);routeSummary=`По дорогам: ${formatDistance(route.distance)} · ${formatDuration(route.duration)}`;map.fitBounds(routeLine.getBounds().pad(.12),{paddingTopLeft:[20,90],paddingBottomRight:[20,155],maxZoom:16});lastRouteOrigin=L.latLng(userLatLng.lat,userLatLng.lng);lastRouteAt=Date.now();setStatus('Маршрут построен')}catch{if(requestId!==routeRequestId)return;if(routeLine){map.removeLayer(routeLine);routeLine=null}if(routeFallbackLine)map.removeLayer(routeFallbackLine);routeFallbackLine=L.polyline([userLatLng,destination],{color:'#2563eb',weight:5,opacity:.8,dashArray:'8 8'}).addTo(map);routeSummary=`Направление: ${formatDistance(userLatLng.distanceTo(destination))}`;map.fitBounds(routeFallbackLine.getBounds().pad(.2),{paddingTopLeft:[20,90],paddingBottomRight:[20,155],maxZoom:16});setStatus('Дорожный маршрут недоступен — показано направление')}finally{if(requestId===routeRequestId){routeBusy=false;renderList()}}}

  locateBtn.onclick=startLocation;
  followBtn.onclick=()=>{followLocation=!followLocation;followBtn.classList.toggle('on',followLocation);if(followLocation&&userLatLng)map.setView(userLatLng,16)};
  map.on('dragstart',()=>{followLocation=false;followBtn.classList.remove('on')});
  Q('handle').onclick=()=>setSheetOpen(!sheet.classList.contains('open'));
  toggleBtn.onclick=()=>setSheetOpen(!sheet.classList.contains('open'));
  selectDay('d27');setTimeout(()=>map.invalidateSize(),120);
})();
